
wp_0: [0, 0, 1, 0, 1.57, 1.57, "tag0"]
wp_1: [1, -1.0, 0, 0, 0, -3.141592653, "map"]
wp_2: [1, -1.0, 0, 0, 0, 0, "map"]
wp_3: [1.5, -1.0, 0, 0, 0, 0, "map"]
wp_4: [0, 0, 1.5, 0, 1.57, 1.57, "tag0"]

