
# wp_0: [1, 2, 3, 4, 5, 6, "tag0"] #1.57079632679
# wp_0: [0, 0, 0.5, 3.14, 1.57, -1.57, "tag0"] #1.57079632679
wp_0: [0, 0, 0.1, -1.57079632679, 1.57079632679, 0, "tag0"] #1.57079632679

# wp_1: [0, 0, 1, 0, 1.57, 1.57, "tag0"]

# wp_1: [1, -1.0, 0, 0, 0, -3.141592653, "map"]
# wp_2: [1, -1.0, 0, 0, 0, 0, "map"]
# wp_3: [1.5, -1.0, 0, 0, 0, 0, "map"]
# wp_4: [0, 0, 1.5, 0, 1.57, 1.57, "tag0"]

# wp_0: [1, 2, 3, 4, 5, pitch, "tag0"]